site_name: Data Science Template
site_description: A comprehensive, customizable template for data science projects
site_url: https://github.com/yourusername/data-science-template
repo_url: https://github.com/yourusername/data-science-template
repo_name: Data Science Template

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/overview.md
      - Directory Structure: architecture/directory-structure.md
      - Core Components: architecture/core-components.md
      - Optional Components: architecture/optional-components.md
      - Configuration: architecture/configuration.md
  - How-To Guides:
      - Getting Started: how-to/getting-started.md
      - Creating a New Project: how-to/creating-new-project.md
      - Adding Epochs: how-to/adding-epochs.md
      - Creating Models: how-to/creating-models.md
      - Documentation: how-to/documentation.md
      - Testing: how-to/testing.md
      - Deployment: how-to/deployment.md
  - Explanation:
      - Design Decisions: explanation/design-decisions.md
      - Epoch-Based Development: explanation/epoch-based-development.md
      - Extending the Template: explanation/extending.md
  - Reference:
      - Project Structure: reference/project-structure.md
      - Utility Functions: reference/utility-functions.md
      - Command Reference: reference/command-reference.md
      - Template Variables: reference/template-variables.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/data-science-template
  version:
    provider: mike
