site_name: '{{ project_name }}'
site_description: '{{ project_desc_short }}'

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_source: true
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes

nav:
  - Home: index.md
  - Tutorials:
      - "Getting Started": tutorials/getting-started.md
  - How-To Guides:
      - how-to/index.md
  - Reference:
      - reference/index.md
      - "API Reference": reference/api/index.md
  - Explanation:
      - explanation/index.md
